application: bphamworld
version: 4
runtime: python
api_version: 1


inbound_services:
- mail

handlers:
- url: /css
  static_dir: static/css
- url: /scripts
  static_dir: static/scripts
- url: /images
  static_dir: static/css/images
  
- url: /favicon\.ico
  static_files: static/css/images/favicon.ico
  upload: static/css/images/favicon\.ico

- url: /.*
  script: main.py

