application: bphamworld
version: 4
runtime: python
api_version: 1

error_handlers:
  - file: templates/404.html

inbound_services:
- mail

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/css/images
  
- url: /favicon\.ico
  static_files: static/css/images/favicon.ico
  upload: static/css/images/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
 
- url: /BingSiteAuth\.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth\.xml

- url: /.*
  script: main.py

