application: bphamworld
version: 4
runtime: python
api_version: 1


inbound_services:
- mail

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
  
- url: /favicon\.ico
  static_files: styles/images/favicon.ico
  upload: styles/images/favicon\.ico

- url: /.*
  script: main.py

